# Generated by Django 5.2.7 on 2025-10-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='AvisoFaltaDagua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Aviso')),
                ('mensagem', models.TextField(verbose_name='Mensagem Completa')),
                ('data_inicio_previsto', models.DateTimeField(verbose_name='Data e Hora de Início Previsto')),
                ('data_fim_previsto', models.DateTimeField(verbose_name='Data e Hora de Fim Previsto')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado para Processamento'), ('CONCLUIDO', 'Concluído')], default='RASCUNHO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Envio')),
                ('bairros_afetados', models.ManyToManyField(to='avisos.bairro', verbose_name='Bairros Afetados')),
            ],
            options={
                'verbose_name': "Aviso de Falta D'água",
                'verbose_name_plural': "Avisos de Falta D'água",
            },
        ),
    ]
